import type { BridgeMessage } from '../types';
import * as Application from 'expo-application';
import dmzLogo from '../../assets/dmz_logo_data.json';

export function createBridgeBootstrap(channel: string, selectedOperator = ''): string {
  const channelLiteral = JSON.stringify(channel);
  const selectedOperatorLiteral = JSON.stringify(selectedOperator.trim());
  const appInfoLiteral = JSON.stringify({
    channel,
    versionName: Application.nativeApplicationVersion ?? '1.1.0',
    versionCode: Application.nativeBuildVersion ?? '176',
    logoUrl: dmzLogo.dataUri
  });

  return [
    '(function () {',
    '  window.__DMZ_APP_INFO = Object.assign({}, window.__DMZ_APP_INFO || {}, ' + appInfoLiteral + ');',
    '  window.__DMZ_RN_PREFERRED_OPERATOR = ' + selectedOperatorLiteral + ';',
    '  if (window.__DMZ_RN_BRIDGE__) { if (window.__dmzRnApplyPreferredOperator) window.__dmzRnApplyPreferredOperator(window.__DMZ_RN_PREFERRED_OPERATOR, 0); return true; }',
    '  window.__DMZ_RN_BRIDGE__ = true;',
    '  function clean(value) { return String(value == null ? "" : value).replace(/\\s+/g, " ").trim(); }',
    '  function send(payload) { try { window.ReactNativeWebView.postMessage(JSON.stringify(payload)); } catch (_) {} }',
    '  function plain(value) { try { var d=document.createElement("div"); d.innerHTML=String(value==null?"":value); return clean(d.textContent||d.innerText||""); } catch (_) { return clean(value); } }',
    '  function badOperatorLabel(value) { value=clean(value); return !value || /SELECT EXISTING OPERATOR|PICK YOUR NAME|RETURNING OPERATOR|YOUR OPERATOR NAME|CHANGE PIN|OPERATOR KILLS/i.test(value); }',
    '  function validOperator(value) { value=clean(value); return value.length>0 && value.length<=80 && !badOperatorLabel(value) && !/[\\r\\n]/.test(value); }',
    '  var operatorState=window.__dmzRnOperatorState||{preferred:"",userEdited:false,applying:false,lastWritten:"",lastAppliedAt:0,refreshTimer:0};',
    '  window.__dmzRnOperatorState=operatorState;',
    '  function directOperatorValues(){',
    '    var input=document.getElementById("playerName"),pick=document.getElementById("playerPick"),typed="",picked="";',
    '    try{typed=clean(input&&(input.value||input.getAttribute("value"))||"");}catch(_){}',
    '    try{if(pick&&pick.selectedIndex>0){var option=pick.options[pick.selectedIndex];picked=clean(pick.value||(option&&(option.value||option.textContent))||"");}}catch(_){}',
    '    return {input:input,pick:pick,typed:typed,picked:picked};',
    '  }',
    '  function registerOperatorControls(){',
    '    var values=directOperatorValues();',
    '    function touched(event){',
    '      if(!event||!event.isTrusted||operatorState.applying)return;',
    '      operatorState.userEdited=true;',
    '      setTimeout(function(){try{readOperator();}catch(_){}},30);',
    '      setTimeout(function(){try{captureBackup();}catch(_){}},420);',
    '    }',
    '    if(values.input&&!values.input.__dmzRnOperatorGuard){values.input.__dmzRnOperatorGuard=true;values.input.addEventListener("input",touched,true);values.input.addEventListener("change",touched,true);}',
    '    if(values.pick&&!values.pick.__dmzRnOperatorGuard){values.pick.__dmzRnOperatorGuard=true;values.pick.addEventListener("change",touched,true);}',
    '    return values;',
    '  }',
    '  function applyPreferredOperator(name, attempt, force) {',
    '    name=clean(name);attempt=Number(attempt||0);force=!!force;if(!validOperator(name))return "empty";',
    '    operatorState.preferred=name;window.__DMZ_RN_PREFERRED_OPERATOR=name;',
    '    try {',
    '      var values=registerOperatorControls(),input=values.input,pick=values.pick,typed=values.typed,picked=values.picked,target=name.toLowerCase();',
    '      var typedDifferent=validOperator(typed)&&typed.toLowerCase()!==target;',
    '      var pickedDifferent=validOperator(picked)&&picked.toLowerCase()!==target;',
    '      if(!force&&operatorState.userEdited){setTimeout(function(){try{readOperator();}catch(_){}},0);return "user";}',
    '      if(!force&&(pickedDifferent||typedDifferent)){setTimeout(function(){try{readOperator();}catch(_){}},0);return "site-current";}',
    '      if(!input&&!pick){if(attempt<24)setTimeout(function(){applyPreferredOperator(name,attempt+1,force);},300);return "wait";}',
    '      operatorState.applying=true;',
    '      var pickMatched=false,changed=false;',
    '      if(pick&&pick.options){for(var i=1;i<pick.options.length;i++){var option=pick.options[i],value=clean(option&&(option.value||option.textContent));if(value.toLowerCase()===target){pickMatched=true;if(pick.selectedIndex!==i){pick.selectedIndex=i;pick.dispatchEvent(new Event("change",{bubbles:true}));changed=true;}break;}}}',
    '      if(input&&clean(input.value).toLowerCase()!==target){input.value=name;input.dispatchEvent(new Event("input",{bubbles:true}));input.dispatchEvent(new Event("change",{bubbles:true}));changed=true;}',
    '      try{if(clean(localStorage.getItem("dmz_myname")||"").toLowerCase()!==target)localStorage.setItem("dmz_myname",name);}catch(_){}',
    '      operatorState.lastWritten=name;operatorState.lastAppliedAt=Date.now();if(force)operatorState.userEdited=false;',
    '      try{if(typeof window.updateNameStatus==="function")window.updateNameStatus();}catch(_){}',
    '      setTimeout(function(){try{readOperator();}catch(_){}},30);',
    '      if((!input||(pick&&!pickMatched))&&attempt<24)setTimeout(function(){applyPreferredOperator(name,attempt+1,force);},300);',
    '      return (input?"ready":"wait")+"|"+(pickMatched?"pick":"nopick")+"|"+(changed?"changed":"same");',
    '    } catch (_) { if(attempt<24)setTimeout(function(){applyPreferredOperator(name,attempt+1,force);},300); return "error"; }',
    '    finally { operatorState.applying=false; }',
    '  }',
    '  window.__dmzRnApplyPreferredOperator = applyPreferredOperator;',
    '  function emit(title, body, key) {',
    '    var text = plain(body);',
    '    if (!text) return;',
    '    window.__dmzRnSeen = window.__dmzRnSeen || {};',
    '    var k = String(key || title + "|" + text);',
    '    var now = Date.now();',
    '    if (now - (window.__dmzRnSeen[k] || 0) < 2500) return;',
    '    window.__dmzRnSeen[k] = now;',
    '    send({ type: "notification", title: clean(title) || "DMZ Ranked", body: text });',
    '  }',
    '  function wrap(name, after) {',
    '    var original = window[name];',
    '    if (typeof original !== "function" || original.__dmzRnWrapped) return;',
    '    var wrapped = function () { var args = arguments; var result = original.apply(this, args); try { after.apply(this, args); } catch (_) {} return result; };',
    '    try { Object.keys(original).forEach(function (key) { wrapped[key] = original[key]; }); } catch (_) {}',
    '    wrapped.__dmzRnWrapped = true;',
    '    window[name] = wrapped;',
    '  }',
    '  function installHooks() {',
    '    wrap("showResult", function (data) { data = data || {}; var before = Number(data.beforeSR || 0); var after = Number(data.afterSR || 0); var delta = after - before; var sign = delta > 0 ? "+" : ""; var place = data.place ? " • #" + data.place + (data.total ? " of " + data.total : "") : ""; emit("[RAID] Raid logged", "Raid logged for " + (data.name || "operator") + " • " + sign + delta + " SR • New total " + after.toLocaleString() + " SR" + place, "raid:" + (data.name || "") + ":" + after + ":" + (data.place || "")); });',
    '    wrap("showHoldNotice", function (reason) { emit("[REVIEW] Raid under review", "Raid submitted and is under review" + (reason ? " • " + clean(reason) : ""), "review:" + clean(reason)); });',
    '    wrap("showBanner", function (_kind, html) { emit("[WEBSITE] Alert", clean(html), "banner:" + clean(html)); });',
    '    wrap("showSeasonPopup", function (season) { season = season || {}; emit("[SEASON] New season", "New season: " + (season.name || "DMZ Ranked season"), "season:" + (season.start || season.name || "")); });',
    '    wrap("buildChangelogPopup", function (entries) { var entry = entries && entries.length ? entries[0] : null; emit("[UPDATE] Website update", entry && entry.title ? "Website update: " + entry.title : "DMZ Ranked website update available", "update:" + (entry && entry.v != null ? entry.v : clean(entry && entry.title))); });',
    '    wrap("showMsg", function (id, kind, text) { text = clean(text); if (id === "logMsg" && kind === "ok" && /^Logged for /i.test(text)) return; emit("[WEBSITE] Alert", text, "msg:" + id + ":" + kind + ":" + text); });',
    '  }',
    '  function currentOperator() {',
    '    try {',
    '      function safeKey(key) { return /operator|player.?name|user.?name|my.?name|callsign|display.?name/i.test(key) && !/pin|pass|token|auth|session|secret|key/i.test(key); }',
    '      function fromObject(obj, depth) { if(!obj||depth>4)return "";if(typeof obj==="string")return validOperator(obj)?clean(obj):"";if(typeof obj!=="object")return "";for(var key in obj){if(!Object.prototype.hasOwnProperty.call(obj,key)||!safeKey(key))continue;var value=obj[key];if(typeof value==="string"&&validOperator(value))return clean(value);if(value&&typeof value==="object"){var nested=fromObject(value,depth+1);if(nested)return nested;}}for(var childKey in obj){if(!Object.prototype.hasOwnProperty.call(obj,childKey))continue;var child=obj[childKey];if(child&&typeof child==="object"){var nestedChild=fromObject(child,depth+1);if(nestedChild)return nestedChild;}}return ""; }',
    '      function fromStorage(storage,label){try{for(var i=0;i<storage.length;i++){var key=storage.key(i)||"";if(!safeKey(key))continue;var raw=storage.getItem(key)||"";if(validOperator(raw))return {name:clean(raw),source:label+" "+key};try{var parsed=JSON.parse(raw),found=fromObject(parsed,0);if(found)return {name:found,source:label+" "+key};}catch(_){}}}catch(_){}return null;}',
    '      var values=registerOperatorControls(),typed=values.typed,picked=values.picked,remembered="";',
    '      try{remembered=clean(localStorage.getItem("dmz_myname")||"");}catch(_){}',
    '      var name="",source="";',
    '      if(validOperator(picked)&&(!validOperator(typed)||typed.toLowerCase()===picked.toLowerCase())){name=picked;source="#playerPick";}',
    '      else if(validOperator(typed)){name=typed;source="#playerName";}',
    '      else if(validOperator(remembered)){name=remembered;source="localStorage dmz_myname";}',
    '      if(!name){var local=fromStorage(window.localStorage,"localStorage");if(local){name=local.name;source=local.source;}}',
    '      if(!name){var session=fromStorage(window.sessionStorage,"sessionStorage");if(session){name=session.name;source=session.source;}}',
    '      var sec=document.getElementById("nameSec"),secText="",secClass="";try{secText=clean(sec&&(sec.textContent||sec.innerText)||"");secClass=clean(sec&&sec.className||"");}catch(_){}',
    '      var visible=!!sec&&sec.style.display!=="none"&&!!secText;',
    '      var verified=visible&&/VERIFIED ON THIS DEVICE/i.test(secText);',
    '      var protectedFlag=visible&&((/\\bprot\\b/i.test(secClass))||(/\\bPROTECTED\\b/i.test(secText)&&!/NOT PROTECTED/i.test(secText)));',
    '      return {name:name,source:source,verified:verified,protected:protectedFlag,statusVisible:visible};',
    '    } catch (_) { return {name:"",source:"",verified:false,protected:false,statusVisible:false}; }',
    '  }',    '  function readOperator() {',
    '    var current = currentOperator();',
    '    var snapshot = JSON.stringify([current.name, current.verified, current.protected, current.source]);',
    '    if (snapshot !== window.__dmzRnLastOperator) {',
    '      window.__dmzRnLastOperator = snapshot;',
    '      send({ type: "operator", name: current.name, verified: current.verified, protected: current.protected, statusVisible: current.statusVisible, source: current.source });',
    '    }',
    '    return current.name;',
    '  }',
    '  function blockedKey(k) { return /pin|pass(word|code)?|token|auth|session|secret|cookie|credential|jwt|bearer|csrf|oauth|api[_.-]?key/i.test(String(k || "")); }',
    '  function blockedValue(v) { v = String(v || ""); if (/eyJ[A-Za-z0-9_-]{8,}\\.[A-Za-z0-9_-]{8,}\\.[A-Za-z0-9_-]{8,}/.test(v)) return true; return /["\x27](?:access_?token|refresh_?token|password|passcode|session|secret|authorization|oauth|jwt|api_?key)["\x27]?\\s*[:=]/i.test(v); }',
    '  function captureBackup(requestId) {',
    '    function fail(reason){if(requestId)send({type:"operator-backup-error",requestId:requestId,reason:reason});return false;}',
    '    try {',
    '      var host = String(location.hostname || "").toLowerCase();',
    '      if (host !== "dmzranked.com" && !host.endsWith(".dmzranked.com")) return fail("not-dmz");',
    '      var current = currentOperator();',
    '      if (!current.name) return fail("no-operator");',
    '      var storage = {}, count = 0, total = 0;',
    '      for (var i = 0; i < localStorage.length; i++) {',
    '        var k = localStorage.key(i) || "";',
    '        if (!k || blockedKey(k)) continue;',
    '        var v = localStorage.getItem(k);',
    '        if (v == null || blockedValue(v) || v.length > 300000) continue;',
    '        var next = total + k.length + v.length;',
    '        if (next > 1000000) break;',
    '        storage[k] = v; count++; total = next;',
    '      }',
    '      if (count <= 0) return fail("no-data");',
    '      storage.dmz_myname = current.name;',
    '      send({ type: "operator-backup", requestId: requestId || "", name: current.name, snapshot: { origin: String(location.origin || "https://dmzranked.com"), storage: storage, count: count, protected: current.protected, verified: current.verified } });',
    '      return true;',
    '    } catch (_) { return fail("capture-failed"); }',
    '  }',
    '  function installSectionNav() {',
    '    if (window.__dmzRnSectionNavInstalled) return;',
    '    var labels=["LEADERBOARD","HOW TO PLAY","LOG A RAID","COMMUNITY","CHAMPIONSHIP","HISTORY","RULES","UPDATES","OVERLAYS","CONTACT","UNOFFICIAL APP","DMZ RANKED APP","DMZ RANKED APP [UNOFFICIAL]"];',
    '    function norm(v){return clean(v).toUpperCase();}',
    '    function known(v){v=norm(v);return labels.indexOf(v)>=0?v:null;}',
    '    function labelFrom(el){var n=el;for(var i=0;i<7&&n;i++,n=n.parentElement){var a="";try{a=known(n.getAttribute&&((n.getAttribute("aria-label")||n.getAttribute("data-tab")||n.getAttribute("data-section")||n.getAttribute("data-page")||n.getAttribute("title"))));}catch(_){}if(a)return a;try{a=known(n.innerText||n.textContent);}catch(_){}if(a)return a;}return null;}',
    '    function candidates(){try{return document.querySelectorAll("button,a,[role=button],[data-tab],[data-section],[data-page],.tab,.nav-button,.menu-button");}catch(_){return [];}}',
    '    function findControl(label){var list=candidates();for(var i=0;i<list.length;i++){if(labelFrom(list[i])===label)return list[i];}return null;}',
    '    function detect(){var list=candidates();for(var i=0;i<list.length;i++){var el=list[i],lab=labelFrom(el);if(!lab)continue;var cls=norm(el.className),aria="";try{aria=norm(el.getAttribute("aria-selected"));}catch(_){}if(aria==="TRUE"||cls.indexOf("ACTIVE")>=0||cls.indexOf("SELECTED")>=0||cls.indexOf("CURRENT")>=0)return lab;}return "LEADERBOARD";}',
    '    var initial=detect(); window.__dmzRnSectionNav={stack:[initial],current:initial,suppress:false};',
    '    document.addEventListener("click",function(ev){var st=window.__dmzRnSectionNav;if(!st||st.suppress)return;var lab=labelFrom(ev.target);if(!lab)return;setTimeout(function(){if(!st.suppress&&st.current!==lab){st.stack.push(lab);st.current=lab;}},0);},true);',
    '    window.__dmzRnSectionBack=function(){try{var st=window.__dmzRnSectionNav;if(!st||st.stack.length<=1)return "empty";st.stack.pop();var prev=st.stack[st.stack.length-1],control=findControl(prev);if(!control)return "missing";st.current=prev;st.suppress=true;control.click();setTimeout(function(){st.suppress=false;},120);return "handled";}catch(_){return "error";}};',
    '    window.__dmzRnSectionNavInstalled=true;',
    '  }',
    '  function visible(el){try{if(!el)return false;var st=getComputedStyle(el),r=el.getBoundingClientRect();return st.display!=="none"&&st.visibility!=="hidden"&&r.width>0&&r.height>0;}catch(_){return !!el;}}',
    '  function scanDomFallbacks(initial) {',
    '    window.__dmzRnDomSeen=window.__dmzRnDomSeen||{};',
    '    function add(prefix,selector,key){var el=null;try{el=document.querySelector(selector);}catch(_){}if(!visible(el))return;var text=plain(el.innerText||el.textContent||"");if(text.length<4||text.length>420)return;var id=key+":"+text;if(window.__dmzRnDomSeen[id])return;window.__dmzRnDomSeen[id]=Date.now();if(!initial)emit(prefix,text,"dom:"+id);}',
    '    add("[WEBSITE] Alert","#banner.banner.show","banner");',
    '    add("[WEBSITE] Alert","#logMsg.msg.show","log");',
    '    add("[RAID] Raid submitted","#resultCard.rcard.show, #resultCard[style*=flex], #resultCard[style*=block]","result");',
    '    add("[SEASON] New season","#seasonPop","season");',
    '    add("[UPDATE] Website update","#clOverlay","change");',
    '  }',
    '  function emitOperatorAlertState(){try{var current=currentOperator(),wanted=clean(current.name);if(!wanted||typeof state==="undefined"||!state||!Array.isArray(state.players)||!Array.isArray(state.raids))return;var p=null;for(var i=0;i<state.players.length;i++){var q=state.players[i];if(q&&clean(q.name).toLowerCase()===wanted.toLowerCase()){p=q;break;}}if(!p)return;var raids={};for(var j=0;j<state.raids.length;j++){var r=state.raids[j];if(!r||r.deleted)continue;var mine=(p.id&&String(r.playerId||"")===String(p.id))||clean(r.playerName).toLowerCase()===clean(p.name||wanted).toLowerCase();if(!mine||!r.id)continue;raids[String(r.id)]={reports:Math.max(0,Number(r.reports)||0),pending:!!r.pending,verified:!!r.verified,pendingReason:clean(r.pendingReason)};}send({type:"operator-alert-state",snapshot:{playerId:String(p.id||""),name:clean(p.name||wanted),reports:Math.max(0,Number(p.reports)||0),raids:raids}});}catch(_){}}',
    '  function refreshOperatorLifecycle(){',
    '    registerOperatorControls();',
    '    var preferred=clean(window.__DMZ_RN_PREFERRED_OPERATOR||operatorState.preferred||"");',
    '    if(preferred)applyPreferredOperator(preferred,0,false);',
    '    readOperator();',
    '  }',
    '  function scheduleOperatorRefresh(){clearTimeout(operatorState.refreshTimer);operatorState.refreshTimer=setTimeout(refreshOperatorLifecycle,90);}',
    '  window.__dmzRnReadOperator = readOperator;',
    '  window.__dmzRnRefreshOperatorLifecycle = refreshOperatorLifecycle;',
    '  window.__dmzRnCaptureBackup = captureBackup;',
    '  window.HarleysStudiosApp = {',
    '    channel: ' + channelLiteral + ',',
    '    notify: function (title, body) { emit(title || "DMZ Ranked", body || "", "manual:" + title + ":" + body); },',
    '    setOperator: function (name, verified) { send({ type: "operator", name: clean(name), verified: !!verified }); },',
    '    openSettings: function (target) { send({ type: "open-settings", target: clean(target) }); },',
    '    log: function (message) { send({ type: "log", message: clean(message) }); }',
    '  };',
    '  window.addEventListener("dmz-ranked-notification", function (event) { var detail = event && event.detail ? event.detail : {}; emit(detail.title || "DMZ Ranked", detail.body || "", "event:" + detail.title + ":" + detail.body); });',
    '  window.addEventListener("dmz-ranked-operator", function () { readOperator(); captureBackup(); });',
    '  installHooks(); installSectionNav(); applyPreferredOperator(window.__DMZ_RN_PREFERRED_OPERATOR, 0, false); readOperator(); scanDomFallbacks(true); emitOperatorAlertState();',
    '  if(!window.__dmzRnObserver){try{var dmzMutationTimer=0;window.__dmzRnObserver=new MutationObserver(function(){if(window.__dmzAppScrolling||window.__dmzAppPaused||dmzMutationTimer)return;dmzMutationTimer=setTimeout(function(){dmzMutationTimer=0;if(window.__dmzAppScrolling||window.__dmzAppPaused)return;installHooks();installSectionNav();scanDomFallbacks(false);scheduleOperatorRefresh();},220);});window.__dmzRnObserver.observe(document.documentElement||document.body,{subtree:true,childList:true});}catch(_){}}',
    '  setInterval(function () { if(window.__dmzAppScrolling||window.__dmzAppPaused)return; installHooks(); installSectionNav(); refreshOperatorLifecycle(); scanDomFallbacks(false); emitOperatorAlertState(); }, 6000);',
    '  send({ type: "ready" });',
    '  return true;',
    '})();',
    'true;'
  ].join('\n');
}

export function parseBridgeMessage(raw: string): BridgeMessage | null {
  try {
    const parsed = JSON.parse(raw) as BridgeMessage;
    if (!parsed || typeof parsed !== 'object' || !('type' in parsed)) return null;
    return parsed;
  } catch {
    return null;
  }
}
