import type { BridgeMessage } from '../types';

export function createBridgeBootstrap(channel: string): string {
  const channelLiteral = JSON.stringify(channel);

  return [
    '(function () {',
    '  if (window.__DMZ_RN_BRIDGE__) return true;',
    '  window.__DMZ_RN_BRIDGE__ = true;',
    '  function clean(value) { return String(value == null ? "" : value).replace(/\\s+/g, " ").trim(); }',
    '  function send(payload) {',
    '    try { window.ReactNativeWebView.postMessage(JSON.stringify(payload)); } catch (_) {}',
    '  }',
    '  function emit(title, body, key) {',
    '    var text = clean(body);',
    '    if (!text) return;',
    '    window.__dmzRnSeen = window.__dmzRnSeen || {};',
    '    var k = String(key || title + "|" + text);',
    '    var now = Date.now();',
    '    if (now - (window.__dmzRnSeen[k] || 0) < 2500) return;',
    '    window.__dmzRnSeen[k] = now;',
    '    send({ type: "notification", title: clean(title) || "DMZ Ranked", body: text });',
    '  }',
    '  function wrap(name, after) {',
    '    var original = window[name];',
    '    if (typeof original !== "function" || original.__dmzRnWrapped) return;',
    '    var wrapped = function () {',
    '      var args = arguments;',
    '      var result = original.apply(this, args);',
    '      try { after.apply(this, args); } catch (_) {}',
    '      return result;',
    '    };',
    '    try { Object.keys(original).forEach(function (key) { wrapped[key] = original[key]; }); } catch (_) {}',
    '    wrapped.__dmzRnWrapped = true;',
    '    window[name] = wrapped;',
    '  }',
    '  function installHooks() {',
    '    wrap("showResult", function (data) {',
    '      data = data || {};',
    '      var before = Number(data.beforeSR || 0);',
    '      var after = Number(data.afterSR || 0);',
    '      var delta = after - before;',
    '      var sign = delta > 0 ? "+" : "";',
    '      emit("Raid logged", "Raid logged for " + (data.name || "operator") + " • " + sign + delta + " SR • New total " + after.toLocaleString() + " SR", "raid:" + (data.name || "") + ":" + after);',
    '    });',
    '    wrap("showHoldNotice", function (reason) {',
    '      emit("Under review", "Raid submitted and is under review" + (reason ? " • " + clean(reason) : ""), "review:" + clean(reason));',
    '    });',
    '    wrap("showBanner", function (_kind, html) { emit("DMZ Ranked", clean(html), "banner:" + clean(html)); });',
    '    wrap("showSeasonPopup", function (season) {',
    '      season = season || {};',
    '      emit("New season", "New season: " + (season.name || "DMZ Ranked season"), "season:" + (season.start || season.name || ""));',
    '    });',
    '    wrap("buildChangelogPopup", function (entries) {',
    '      var entry = entries && entries.length ? entries[0] : null;',
    '      emit("Website update", entry && entry.title ? "Website update: " + entry.title : "DMZ Ranked website update available", "update:" + (entry && entry.v != null ? entry.v : clean(entry && entry.title)));',
    '    });',
    '    wrap("showMsg", function (id, kind, text) {',
    '      text = clean(text);',
    '      if (id === "logMsg" && kind === "ok" && /^Logged for /i.test(text)) return;',
    '      emit("DMZ Ranked", text, "msg:" + id + ":" + kind + ":" + text);',
    '    });',
    '  }',
    '  function readOperator() {',
    '    try {',
    '      var input = document.getElementById("playerName");',
    '      var pick = document.getElementById("playerPick");',
    '      var typed = clean(input && (input.value || input.getAttribute("value")));',
    '      var picked = "";',
    '      if (pick && pick.selectedIndex > 0) {',
    '        var option = pick.options[pick.selectedIndex];',
    '        picked = clean(pick.value || (option && (option.value || option.textContent)));',
    '      }',
    '      var remembered = "";',
    '      try { remembered = clean(localStorage.getItem("dmz_myname") || ""); } catch (_) {}',
    '      var name = picked || typed || remembered;',
    '      var source = picked ? "#playerPick" : typed ? "#playerName" : remembered ? "localStorage dmz_myname" : "";',
    '      var sec = document.getElementById("nameSec");',
    '      var secText = clean(sec && (sec.textContent || sec.innerText));',
    '      var visible = !!sec && sec.style.display !== "none" && !!secText;',
    '      var verified = visible && /VERIFIED ON THIS DEVICE/i.test(secText);',
    '      var protectedFlag = visible && /\\bPROTECTED\\b/i.test(secText) && !/NOT PROTECTED/i.test(secText);',
    '      var snapshot = JSON.stringify([name, verified, protectedFlag, source]);',
    '      if (snapshot !== window.__dmzRnLastOperator) {',
    '        window.__dmzRnLastOperator = snapshot;',
    '        send({ type: "operator", name: name, verified: verified, protected: protectedFlag, source: source });',
    '      }',
    '      return name;',
    '    } catch (_) { return ""; }',
    '  }',
    '  window.__dmzRnReadOperator = readOperator;',
    '  window.HarleysStudiosApp = {',
    '    channel: ' + channelLiteral + ',',
    '    notify: function (title, body) { emit(title || "DMZ Ranked", body || "", "manual:" + title + ":" + body); },',
    '    setOperator: function (name, verified) { send({ type: "operator", name: clean(name), verified: !!verified }); },',
    '    openSettings: function () { send({ type: "open-settings" }); },',
    '    log: function (message) { send({ type: "log", message: clean(message) }); }',
    '  };',
    '  window.addEventListener("dmz-ranked-notification", function (event) {',
    '    var detail = event && event.detail ? event.detail : {};',
    '    emit(detail.title || "DMZ Ranked", detail.body || "", "event:" + detail.title + ":" + detail.body);',
    '  });',
    '  window.addEventListener("dmz-ranked-operator", function () { readOperator(); });',
    '  installHooks();',
    '  readOperator();',
    '  setInterval(function () { installHooks(); readOperator(); }, 1800);',
    '  send({ type: "ready" });',
    '  return true;',
    '})();',
    'true;'
  ].join('\n');
}

export function parseBridgeMessage(raw: string): BridgeMessage | null {
  try {
    const parsed = JSON.parse(raw) as BridgeMessage;
    if (!parsed || typeof parsed !== 'object' || !('type' in parsed)) {
      return null;
    }
    return parsed;
  } catch {
    return null;
  }
}
