import type { BridgeMessage } from '../types';
import * as Application from 'expo-application';
import dmzLogo from '../../assets/dmz_logo_data.json';

export function createBridgeBootstrap(channel: string): string {
  const channelLiteral = JSON.stringify(channel);
  const appInfoLiteral = JSON.stringify({
    channel,
    versionName: Application.nativeApplicationVersion ?? '1.0.62',
    versionCode: Application.nativeBuildVersion ?? '166',
    logoUrl: dmzLogo.dataUri
  });

  return [
    '(function () {',
    '  window.__DMZ_APP_INFO = Object.assign({}, window.__DMZ_APP_INFO || {}, ' + appInfoLiteral + ');',
    '  if (window.__DMZ_RN_BRIDGE__) return true;',
    '  window.__DMZ_RN_BRIDGE__ = true;',
    '  function clean(value) { return String(value == null ? "" : value).replace(/\\s+/g, " ").trim(); }',
    '  function send(payload) { try { window.ReactNativeWebView.postMessage(JSON.stringify(payload)); } catch (_) {} }',
    '  function emit(title, body, key) {',
    '    var text = clean(body);',
    '    if (!text) return;',
    '    window.__dmzRnSeen = window.__dmzRnSeen || {};',
    '    var k = String(key || title + "|" + text);',
    '    var now = Date.now();',
    '    if (now - (window.__dmzRnSeen[k] || 0) < 2500) return;',
    '    window.__dmzRnSeen[k] = now;',
    '    send({ type: "notification", title: clean(title) || "DMZ Ranked", body: text });',
    '  }',
    '  function wrap(name, after) {',
    '    var original = window[name];',
    '    if (typeof original !== "function" || original.__dmzRnWrapped) return;',
    '    var wrapped = function () { var args = arguments; var result = original.apply(this, args); try { after.apply(this, args); } catch (_) {} return result; };',
    '    try { Object.keys(original).forEach(function (key) { wrapped[key] = original[key]; }); } catch (_) {}',
    '    wrapped.__dmzRnWrapped = true;',
    '    window[name] = wrapped;',
    '  }',
    '  function installHooks() {',
    '    wrap("showResult", function (data) { data = data || {}; var before = Number(data.beforeSR || 0); var after = Number(data.afterSR || 0); var delta = after - before; var sign = delta > 0 ? "+" : ""; emit("[RAID] Raid logged", "Raid logged for " + (data.name || "operator") + " • " + sign + delta + " SR • New total " + after.toLocaleString() + " SR", "raid:" + (data.name || "") + ":" + after); });',
    '    wrap("showHoldNotice", function (reason) { emit("[REVIEW] Raid under review", "Raid submitted and is under review" + (reason ? " • " + clean(reason) : ""), "review:" + clean(reason)); });',
    '    wrap("showBanner", function (_kind, html) { emit("[WEBSITE] Alert", clean(html), "banner:" + clean(html)); });',
    '    wrap("showSeasonPopup", function (season) { season = season || {}; emit("[SEASON] New season", "New season: " + (season.name || "DMZ Ranked season"), "season:" + (season.start || season.name || "")); });',
    '    wrap("buildChangelogPopup", function (entries) { var entry = entries && entries.length ? entries[0] : null; emit("[UPDATE] Website update", entry && entry.title ? "Website update: " + entry.title : "DMZ Ranked website update available", "update:" + (entry && entry.v != null ? entry.v : clean(entry && entry.title))); });',
    '    wrap("showMsg", function (id, kind, text) { text = clean(text); if (id === "logMsg" && kind === "ok" && /^Logged for /i.test(text)) return; emit("[WEBSITE] Alert", text, "msg:" + id + ":" + kind + ":" + text); });',
    '  }',
    '  function currentOperator() {',
    '    try {',
    '      var input = document.getElementById("playerName");',
    '      var pick = document.getElementById("playerPick");',
    '      var typed = clean(input && (input.value || input.getAttribute("value")));',
    '      var picked = "";',
    '      if (pick && pick.selectedIndex > 0) { var option = pick.options[pick.selectedIndex]; picked = clean(pick.value || (option && (option.value || option.textContent))); }',
    '      var remembered = "";',
    '      try { remembered = clean(localStorage.getItem("dmz_myname") || ""); } catch (_) {}',
    '      var name = picked || typed || remembered;',
    '      var source = picked ? "#playerPick" : typed ? "#playerName" : remembered ? "localStorage dmz_myname" : "";',
    '      var sec = document.getElementById("nameSec");',
    '      var secText = clean(sec && (sec.textContent || sec.innerText));',
    '      var visible = !!sec && sec.style.display !== "none" && !!secText;',
    '      var verified = visible && /VERIFIED ON THIS DEVICE/i.test(secText);',
    '      var protectedFlag = visible && /\\bPROTECTED\\b/i.test(secText) && !/NOT PROTECTED/i.test(secText);',
    '      return { name: name, source: source, verified: verified, protected: protectedFlag };',
    '    } catch (_) { return {name:"",source:"",verified:false,protected:false}; }',
    '  }',
    '  function readOperator() {',
    '    var current = currentOperator();',
    '    var snapshot = JSON.stringify([current.name, current.verified, current.protected, current.source]);',
    '    if (snapshot !== window.__dmzRnLastOperator) {',
    '      window.__dmzRnLastOperator = snapshot;',
    '      send({ type: "operator", name: current.name, verified: current.verified, protected: current.protected, source: current.source });',
    '    }',
    '    return current.name;',
    '  }',
    '  function blockedKey(k) { return /pin|pass(word|code)?|token|auth|session|secret|cookie|credential|jwt|bearer|csrf|oauth|api[_.-]?key/i.test(String(k || "")); }',
    '  function blockedValue(v) { v = String(v || ""); if (/eyJ[A-Za-z0-9_-]{8,}\\.[A-Za-z0-9_-]{8,}\\.[A-Za-z0-9_-]{8,}/.test(v)) return true; return /["\x27](?:access_?token|refresh_?token|password|passcode|session|secret|authorization|oauth|jwt|api_?key)["\x27]?\\s*[:=]/i.test(v); }',
    '  function captureBackup() {',
    '    try {',
    '      var host = String(location.hostname || "").toLowerCase();',
    '      if (host !== "dmzranked.com" && !host.endsWith(".dmzranked.com")) return false;',
    '      var current = currentOperator();',
    '      if (!current.name) return false;',
    '      var storage = {}, count = 0, total = 0;',
    '      for (var i = 0; i < localStorage.length; i++) {',
    '        var k = localStorage.key(i) || "";',
    '        if (!k || blockedKey(k)) continue;',
    '        var v = localStorage.getItem(k);',
    '        if (v == null || blockedValue(v) || v.length > 300000) continue;',
    '        var next = total + k.length + v.length;',
    '        if (next > 1000000) break;',
    '        storage[k] = v; count++; total = next;',
    '      }',
    '      storage.dmz_myname = current.name;',
    '      send({ type: "operator-backup", name: current.name, snapshot: { origin: String(location.origin || "https://dmzranked.com"), storage: storage, count: count, protected: current.protected, verified: current.verified } });',
    '      return true;',
    '    } catch (_) { return false; }',
    '  }',
    '  window.__dmzRnReadOperator = readOperator;',
    '  window.__dmzRnCaptureBackup = captureBackup;',
    '  window.HarleysStudiosApp = {',
    '    channel: ' + channelLiteral + ',',
    '    notify: function (title, body) { emit(title || "DMZ Ranked", body || "", "manual:" + title + ":" + body); },',
    '    setOperator: function (name, verified) { send({ type: "operator", name: clean(name), verified: !!verified }); },',
    '    openSettings: function () { send({ type: "open-settings" }); },',
    '    log: function (message) { send({ type: "log", message: clean(message) }); }',
    '  };',
    '  window.addEventListener("dmz-ranked-notification", function (event) { var detail = event && event.detail ? event.detail : {}; emit(detail.title || "DMZ Ranked", detail.body || "", "event:" + detail.title + ":" + detail.body); });',
    '  window.addEventListener("dmz-ranked-operator", function () { readOperator(); captureBackup(); });',
    '  installHooks(); readOperator();',
    '  setInterval(function () { installHooks(); readOperator(); }, 1800);',
    '  send({ type: "ready" });',
    '  return true;',
    '})();',
    'true;'
  ].join('\n');
}

export function parseBridgeMessage(raw: string): BridgeMessage | null {
  try {
    const parsed = JSON.parse(raw) as BridgeMessage;
    if (!parsed || typeof parsed !== 'object' || !('type' in parsed)) return null;
    return parsed;
  } catch {
    return null;
  }
}
