plugins {
    id 'com.android.application'
}

android {
    namespace 'com.harleytg.dmzrankedunofficial'
    compileSdk 36

    defaultConfig {
        applicationId 'com.harleytg.dmzrankedunofficial'
        minSdk 26
        targetSdk 36
        versionCode 111
        versionName '1.0.11'
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
